paths:
  data_root: "D:/"

# Number of conditioned stimulus (CS), or pairs of US-CS
num_cs: 6

# Number of sessioins included in working_dir
# Each session is considered to have the same timing of CS for all mice in that session. If not, contact @nobel_sean
num_sessions: 1
